tools:
    # Code Coverage
    external_code_coverage:
        enabled: true
        timeout: 300
        filter:
            excluded_paths:
                - 'vendor/*'


    php_code_coverage:
        enabled:              false
        test_command:         phpunit
        filter:
            excluded_paths:
                - 'vendor/*'

